### ISSUE TITLE
IoT.js API for external modules

### ISSUE THREAD

**Issue by galpeter** [pando-project/iotjs#1476]
IoT.js currently does not explicitly states what C API functions can be used when writing external C modules. 
Thus if someone writes C modules the `iotjs_def.h` is used. But it is not clear how an external module use the internal parts of IoT.js, for example: http/https requests, file operations, libtuv elements, etc.

It would be good to have a well defined C API (something similar like the `jerryscript.h` in the jerryscript project) as it would ease the module developer's life. Additionally it would pave the way for dynamically loadable modules.

(For JS modules it is clear what JS calls are supported (via require calls).)

**Comment by galpeter** [comment]
A related part: I've created a module which can load shared objects (on linux systems currently).
Module link: https://github.com/galpeter/shoml
It also contains an example loadable shared object.

**Comment by zherczeg** [comment]
The loadable object interface is very sensitive to the API. So we need a versioned API, where the module tells its own API version, and IoT.js decides whether that version is supported. 

The minimum API is defining an init function which returns with a JerryScript object. I think the JerryScript API should be part of the IoT.js API. Perhaps we need functions to load other modules. Maybe this is enough for start.

**Comment by rzr** [comment]
Does this relate somehow to N-API support ?

https://nodejs.org/api/n-api.html#n_api_n_api

I know that @gabrielschulhof (of Iotivity-node) was supportive on this.

I'll be curious to know about the status of this idea.

**Comment by gabrielschulhof** [comment]
@rzr I contributed the [module API](https://github.com/jerryscript-project/jerryscript/blob/master/docs/12.EXT-REFERENCE-MODULE.md) to JerryScript because it's a prerequisite for N-API. However, the JerryScript module API can definitely be used today, even before JerryScript is exposed via N-API.

I'm still working on N-API, but I need the followings from JerryScript in order to complete it (list likely not complete as I still haven't attempted running all Node.js N-API tests on JerryScript):
* Symbols
* `jerry_arraybuffer_get_pointer()` to return a pointer even if it's internal to JerryScript

**Comment by daeyeon** [comment]
This is about IoT.js specific native APIs for external modules. I think that it's a different story to support Node.js modules which are built using N-API.
